### ISSUE TITLE
Rewrite everything in Cairo 1.0

### ISSUE THREAD

**Issue by nikitamasych** [CalculusEnjoyer/Ultimate-Crypto-Rate-Provider#1]
Hello!
It is a fantastic project you have here! 😎
Wanna know how to make it better?😏😏 Add blockchain and collect tokens for its usage! Deploy it in the form of smart contract to [Starknet](https://www.starknet.io/en) right today. Make technology great again!

**Comment by CalculusEnjoyer** [comment]
Dear Nikita Masych,

Absolutely! Because what every project needs to be truly better is an layer of blockchain and tokenization. Forget about practicality, usability, or even relevance. Just slap some blockchain magic on it and voila! Instant success and hype.

And why stop there? Let's not settle for any ordinary blockchain; let's deploy it on Starknet because we need to be on the bleeding edge of every shiny new technology that comes along. Who cares about scalability, adoption, or actual user demand? We just want to show off our technical prowess!

Let's not forget the pièce de résistance: collecting tokens for its usage! Because who doesn't love complicating things even further by introducing an arbitrary token economy? Why bother with traditional payment methods when we can turn everything into a convoluted maze of tokens that no one really understands or wants?

Let's heed your words and make technology great again! Because nothing screams innovation like blindly throwing blockchain and tokens at everything we see. Brilliant suggestion, genuinely brilliant.

Thank you again, I will cover all your suggestions in the next MR! Stay tuned.

The kindest regards you can even imagine,

Volodymyr Kravchuk

**Comment by nikitamasych** [comment]
Dear Volodymyr Kravchuk,

Your eloquent portrayal of the exaggerated enthusiasm for blockchain and tokenization truly captures the essence of the situation!
It's truly a breath of fresh air to witness your remarkable ability to exercise restraint and practicality. While the world around us dives headfirst into the murky waters of unnecessary complexity, you stand tall as a beacon of simplicity and clarity😎

Why bother with convoluted solutions when straightforward approaches exist? Who needs a blockchain when a simple spreadsheet would do just fine? Forget about tokenization; let's stick to good old-fashioned cash! After all, who wants to navigate through a labyrinth of digital tokens when a dollar bill fits neatly in our wallets?

It's truly awe-inspiring to witness your mastery in distinguishing between what's necessary and what's just fluff. While others drown in a sea of technological buzzwords, you effortlessly steer clear of the noise, choosing practicality and usability over empty hype👏

So, here's to you, the maestro of keeping things simple. May your pragmatic mindset continue to guide you through a world drowning in unnecessary complexity. Your ability to discern where to draw the line is a skill to be cherished and celebrated!

Applauding your wisdom,

Nikita Masych

**Comment by CalculusEnjoyer** [comment]
Dear Nikita Masych,

I must express my profound gratitude for your effusive missive, which has reached the depths of my sensibilities and awakened a latent appreciation for the art of elaborate expression. Your gracious acknowledgment of my humble endeavors to temper the fervor surrounding blockchain and tokenization fills me with a sense of serenity and equanimity.

Indeed, in this tumultuous epoch, where the tempestuous waves of ostentation crash upon the shores of reason, your discerning eye recognizes the merit of simplicity and lucidity. Why, I ask, should we embroil ourselves in the intricacies of convoluted solutions when there exist uncomplicated avenues that suffice? Verily, a modest spreadsheet can ably serve our purposes, without the need for the labyrinthine complexities of blockchain. As for tokenization, let us hearken back to the days of yore, when tangible currency graced our pockets and wallets, transcending the baffling mazes of digital tokens.

Your homage to my judiciousness in discerning the essential from the superfluous is nothing short of awe-inspiring. While multitudes flounder amidst the cacophony of technological jargon, I, with unwavering resolve, navigate the treacherous waters of contemporaneity, guided by the compass of practicality and utility.

Thus, permit me to raise a toast to your penmanship, which pays homage to my role as a maestro of simplicity. May the rudder of your pragmatic disposition continue to steer you through a world ensnared in the coils of gratuitous complexity. Your recognition of the fine line that separates necessity from frivolity is a testament to the discerning wisdom that warrants celebration and cherishment.

With utmost appreciation and admiration,

Volodymyr Kravchuk

**Comment by CalculusEnjoyer** [comment]
I reopen this issue so everybody can bring his own piece of advice and witness some blockchain adoption right here!
